controller:
  replicaCount: 3
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      cloud.google.com/load-balancer-type: "External"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  admissionWebhooks:
    enabled: true
    patch:
      nodeSelector:
        kubernetes.io/os: linux

rbac:
  create: true

serviceAccount:
  create: true
  name: nginx-ingress-serviceaccount

config:
  use-forwarded-headers: "true"

podSecurityPolicy:
  enabled: true
